name: Sample Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: |
            echo "Hello World!"
            echo "running multi line shell commands is possible"
      - name: Print goodbye
        run: echo "Bye!"
 
