name: deployment-exercise
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3.3.0
        # 다운로드 완료
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache
        # npm: npm ci
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
