name: deploy website
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3.3.0
      - name: install dependencies
        run: yarn install --immutable --immutable-cache --check-cache
      - name: lint
        run: yarn lint
      - name: test
        run: yarn test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Build website
        run: yarn build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying..."
