name: pull request events
on:
  pull_request:
    types:
      - opened
      # 누군가가 fork한 뒤 dev-*로 올리는 PR에 대해서는 트리거되지 않음. fork는 누구나 할 수 있기 때문에 항상 가능해진다면 부하를 일으키게 할 수 있음
      - "dev-*"
  workflow_dispatch:
  push:
    branches:
      - main
      # ex) dev-로 시작하는 모든브랜치
      - "dev-*"
      # asterisk가 두개인 경우는 2개 이상의 slash도 허용
      - "feat/**"
    # 이 경우엔 무시. paths: 인 경우 이 path 내 code change가 푸시될 때만 트리거
    paths-ignore:
      - ".github/workflows/*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: install node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: yarn install --immutable --immutable-cache --check-cache
      - name: test
        run: yarn test
      - name: Build
        run: yarn build
      - name: deploy
        run: echo "deployed!"
